const en_dict = Object.freeze({
    title: 'Crown Travel',
    brandName: 'Crown Travel',
    navDiscover: 'Discover',
    navAbout: 'About Ha Long Bay',
    navBooking: 'Book Flight',
    btnLogin: 'Login',
    btnRegister: 'Register',
    heroTitle: 'Discover the Wonder of Ha Long Bay',
    heroSubtitle: 'Experience the magic of Vietnam\'s most iconic destination',
    btnExplore: 'Book Your Adventure',
    aboutTitle: 'About Ha Long Bay',
    aboutDescription: 'Ha Long Bay, located in northern Vietnam, is one of the world\'s most stunning natural wonders. With over 1,600 limestone islands rising dramatically from emerald waters, it\'s a UNESCO World Heritage Site that captivates visitors with breathtaking beauty and adventure opportunities.',
    feature1Title: 'Crystal Clear Waters',
    feature1Description: 'Swim in pristine emerald waters surrounded by dramatic limestone cliffs.',
    feature2Title: 'Island Hopping',
    feature2Description: 'Explore hundreds of scenic islands and hidden caves by traditional boat.',
    feature3Title: 'Unforgettable Sunsets',
    feature3Description: 'Witness breathtaking sunsets from the water as day fades into dusk.',
    feature4Title: 'Adventure Activities',
    feature4Description: 'Rock climbing, kayaking, and diving for the thrill-seekers.',
    bookingTitle: 'Book Your Flight',
    bookingSubtitle: 'Start your journey to Ha Long Bay today',
    labelFrom: 'From',
    labelTo: 'To',
    labelDeparture: 'Departure Date',
    labelReturn: 'Return Date',
    labelPassengers: 'Passengers',
    labelClass: 'Class',
    placeholderFrom: 'Departure City',
    placeholderTo: 'Ha Long Bay, Vietnam',
    optionEconomy: 'Economy',
    optionPremium: 'Premium Economy',
    optionBusiness: 'Business',
    optionFirst: 'First Class',
    btnSearch: 'Search Flights',
    footerCompany: 'Company',
    footerAbout: 'About Us',
    footerCareer: 'Careers',
    footerPress: 'Press',
    footerSupport: 'Support',
    footerContact: 'Contact Us',
    footerFAQ: 'FAQ',
    footerHelp: 'Help Center',
    footerLegal: 'Legal',
    footerPrivacy: 'Privacy Policy',
    footerTerms: 'Terms of Service',
    footerCookies: 'Cookie Policy',
    footerCopyright: '© 2026 Crown Travel. All rights reserved.',
});

export default en_dict;
