const es_dict = Object.freeze({
    title: 'Crown Travel',
    brandName: 'Crown Travel',
    navDiscover: 'Descubrir',
    navAbout: 'Sobre Ha Long Bay',
    navBooking: 'Reservar Vuelo',
    btnLogin: 'Iniciar sesión',
    btnRegister: 'Registrarse',
    heroTitle: 'Descubre la maravilla de Ha Long Bay',
    heroSubtitle: 'Experimenta la magia del destino más icónico de Vietnam',
    btnExplore: 'Reserva tu aventura',
    aboutTitle: 'Sobre Ha Long Bay',
    aboutDescription: 'Ha Long Bay, ubicado en el norte de Vietnam, es una de las maravillas naturales más impresionantes del mundo. Con más de 1.600 islas kársticas que emergen de aguas color esmeralda, es un sitio Patrimonio de la Humanidad de la UNESCO que cautiva con su belleza y aventuras.',
    feature1Title: 'Aguas cristalinas',
    feature1Description: 'Nada en aguas color esmeralda rodeadas de acantilados de piedra caliza.',
    feature2Title: 'Recorrido por islas',
    feature2Description: 'Explora cientos de islas y cuevas ocultas en barco tradicional.',
    feature3Title: 'Atardeceres inolvidables',
    feature3Description: 'Disfruta puestas de sol impresionantes mientras el día se desvanece.',
    feature4Title: 'Actividades de aventura',
    feature4Description: 'Escalada, kayak y buceo para los amantes de la emoción.',
    bookingTitle: 'Reserva tu vuelo',
    bookingSubtitle: 'Comienza tu viaje a Ha Long Bay hoy',
    labelFrom: 'Desde',
    labelTo: 'Hasta',
    labelDeparture: 'Fecha de salida',
    labelReturn: 'Fecha de regreso',
    labelPassengers: 'Pasajeros',
    labelClass: 'Clase',
    placeholderFrom: 'Ciudad de salida',
    placeholderTo: 'Ha Long Bay, Vietnam',
    optionEconomy: 'Económica',
    optionPremium: 'Premium Economy',
    optionBusiness: 'Business',
    optionFirst: 'Primera Clase',
    btnSearch: 'Buscar vuelos',
    footerCompany: 'Empresa',
    footerAbout: 'Sobre nosotros',
    footerCareer: 'Carreras',
    footerPress: 'Prensa',
    footerSupport: 'Soporte',
    footerContact: 'Contáctanos',
    footerFAQ: 'Preguntas frecuentes',
    footerHelp: 'Centro de ayuda',
    footerLegal: 'Legal',
    footerPrivacy: 'Política de privacidad',
    footerTerms: 'Términos del servicio',
    footerCookies: 'Política de cookies',
    footerCopyright: '© 2026 Crown Travel. Todos los derechos reservados.',
});

export default es_dict;
