const pt_dict = Object.freeze({
    title: 'Crown Travel',
    brandName: 'Crown Travel',
    navDiscover: 'Descobrir',
    navAbout: 'Sobre Ha Long Bay',
    navBooking: 'Reservar Voo',
    btnLogin: 'Login',
    btnRegister: 'Cadastrar-se',
    heroTitle: 'Descubra a maravilha de Ha Long Bay',
    heroSubtitle: 'Experimente a magia do destino mais icônico do Vietnã',
    btnExplore: 'Reserve sua aventura',
    aboutTitle: 'Sobre Ha Long Bay',
    aboutDescription: 'Ha Long Bay, localizado no norte do Vietnã, é uma das maravilhas naturais mais impressionantes do mundo. Com mais de 1.600 ilhas de calcário surgindo em águas esmeralda, é um Patrimônio Mundial da UNESCO que cativa visitantes com sua beleza e oportunidades de aventura.',
    feature1Title: 'Águas cristalinas',
    feature1Description: 'Nade em águas esmeralda cercadas por dramáticos penhascos de calcário.',
    feature2Title: 'Passeio de ilhas',
    feature2Description: 'Explore centenas de ilhas e cavernas escondidas em barco tradicional.',
    feature3Title: 'Pôr do sol inesquecíveis',
    feature3Description: 'Presencie pores do sol impressionantes enquanto o dia se transforma.',
    feature4Title: 'Atividades de aventura',
    feature4Description: 'Escalada, caiaque e mergulho para os amantes de emoção.',
    bookingTitle: 'Reserve seu voo',
    bookingSubtitle: 'Comece sua jornada para Ha Long Bay hoje',
    labelFrom: 'De',
    labelTo: 'Para',
    labelDeparture: 'Data de partida',
    labelReturn: 'Data de retorno',
    labelPassengers: 'Passageiros',
    labelClass: 'Classe',
    placeholderFrom: 'Cidade de partida',
    placeholderTo: 'Ha Long Bay, Vietnã',
    optionEconomy: 'Econômica',
    optionPremium: 'Premium Economy',
    optionBusiness: 'Business',
    optionFirst: 'Primeira Classe',
    btnSearch: 'Buscar voos',
    footerCompany: 'Empresa',
    footerAbout: 'Sobre nós',
    footerCareer: 'Carreiras',
    footerPress: 'Imprensa',
    footerSupport: 'Suporte',
    footerContact: 'Contate-nos',
    footerFAQ: 'FAQ',
    footerHelp: 'Central de Ajuda',
    footerLegal: 'Legal',
    footerPrivacy: 'Política de Privacidade',
    footerTerms: 'Termos de Serviço',
    footerCookies: 'Política de Cookies',
    footerCopyright: '© 2026 Crown Travel. Todos os direitos reservados.',
});

export default pt_dict;
